/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSubredditRouteImport } from './routes/r/$subreddit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSubredditRoute = RSubredditRouteImport.update({
  id: '/r/$subreddit',
  path: '/r/$subreddit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$subreddit': typeof RSubredditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$subreddit': typeof RSubredditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r/$subreddit': typeof RSubredditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/r/$subreddit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/r/$subreddit'
  id: '__root__' | '/' | '/r/$subreddit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RSubredditRoute: typeof RSubredditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$subreddit': {
      id: '/r/$subreddit'
      path: '/r/$subreddit'
      fullPath: '/r/$subreddit'
      preLoaderRoute: typeof RSubredditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RSubredditRoute: RSubredditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
